### ISSUE TITLE
undefined 'end_time' if index is 0

### ISSUE THREAD

**Issue by ta1986** [stream-monkey/aws-transcribe-to-vtt#8]
I got :

TypeError: Cannot read property 'end_time' of undefined
    at /aws-transcribe-to-vtt-master/lib/vttConvert.js:48:72
    at eachOfArrayLike (/aws-transcribe-to-vtt-master/node_modules/async/dist/async.js:1069:9)
    at Object.eachOf (/aws-transcribe-to-vtt-master/node_modules/async/dist/async.js:1117:5)
...

Add a condition to check if index == 0 will fix it.

**Comment by paullegrand** [comment]
@ta1986 would you like to make a pull request with your proposed fix?

**Comment by paullegrand** [comment]
Closed via https://github.com/stream-monkey/aws-transcribe-to-vtt/pull/9
